name: 'dartfeed'
version: 0.0.1
description: A web server built using the shelf package.
#author: testuset <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  args: any
  shelf: ^0.6.0
  rpc: ^0.5.7
  shelf_exception_handler: ^0.1.0
  shelf_rpc: ^0.0.3
  logging_handlers: ^0.8.0
  meta: ^1.0.4
  uuid: any
  mongo_dart: ^0.2.10
  xml: ^2.5.0
  connection_pool: ^0.1.2
  angular2: ^2.2.0
  angular2_components: any
  options_file: any
  http: '>=0.11.1 <0.12.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  mime: any
  option: any
  dart_feed: any
  bson: any
dependency_overrides:
  uri:
    git: https://github.com/google/uri.dart.git
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter